import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { JOB_STATUS, jobStore } from './jobStore.js';
import { identifyViralClips, renderThumbnail, transcribeYouTubeUrl, trimVideo, writeThumbnailPrompt } from './services.js';
import { setThumbnail, uploadVideo } from './youtube.js';

export async function runJob(jobId, auth) {
  const job = jobStore.getJob(jobId);
  if (!job) return;

  const tempDir = await fs.mkdtemp(path.join(os.tmpdir(), `getchopped-${jobId}-`));
  jobStore.updateJob(jobId, { status: JOB_STATUS.RUNNING });
  jobStore.log(jobId, `Pipeline started in ${tempDir}.`);

  try {
    jobStore.log(jobId, 'Transcribing source video with RapidAPI Speech-to-Text AI.');
    const transcript = await transcribeYouTubeUrl(job.sourceUrl);
    jobStore.log(jobId, `Transcript normalized: ${transcript.segments.length} segments, ${transcript.text.length} characters.`);

    jobStore.log(jobId, 'Asking Claude to identify viral clip moments.');
    const clipPlans = await identifyViralClips(transcript);
    jobStore.log(jobId, `Claude selected ${clipPlans.length} clip moments.`);

    for (const [index, plan] of clipPlans.entries()) {
      const clip = jobStore.addClip(jobId, {
        ...plan,
        status: 'running',
        index: index + 1
      });

      jobStore.log(jobId, `Clip ${index + 1}: generating thumbnail prompt.`);
      const thumbnailPrompt = await writeThumbnailPrompt(plan, transcript);
      jobStore.updateClip(jobId, clip.id, { thumbnailPrompt });

      const thumbnailPath = path.join(tempDir, `clip-${index + 1}-thumbnail.png`);
      try {
        jobStore.log(jobId, `Clip ${index + 1}: rendering 1280x720 thumbnail.`);
        await renderThumbnail(thumbnailPrompt, thumbnailPath);
        jobStore.updateClip(jobId, clip.id, { thumbnailPath });
      } catch (error) {
        jobStore.log(jobId, `Clip ${index + 1}: thumbnail generation failed, upload will continue. ${error.message}`, 'warn');
      }

      const outputPath = path.join(tempDir, `clip-${index + 1}.mp4`);
      jobStore.log(jobId, `Clip ${index + 1}: trimming ${plan.startSec}s to ${plan.endSec}s with FFmpeg.`);
      await trimVideo({
        sourceUrl: job.sourceUrl,
        startSec: plan.startSec,
        endSec: plan.endSec,
        outputPath
      });
      jobStore.updateClip(jobId, clip.id, { outputPath });

      jobStore.log(jobId, `Clip ${index + 1}: uploading to YouTube.`);
      const upload = await uploadVideo(auth, {
        filePath: outputPath,
        title: plan.title,
        description: `${plan.description}\n\nHook: ${plan.hook}\n\nGenerated by GetChopped.`,
        tags: plan.tags
      });
      jobStore.updateClip(jobId, clip.id, {
        youtubeId: upload.id,
        youtubeUrl: upload.url,
        status: 'uploaded'
      });

      if (await exists(thumbnailPath)) {
        try {
          jobStore.log(jobId, `Clip ${index + 1}: setting YouTube thumbnail.`);
          await setThumbnail(auth, upload.id, thumbnailPath);
          jobStore.updateClip(jobId, clip.id, { thumbnailStatus: 'set' });
        } catch (error) {
          jobStore.log(jobId, `Clip ${index + 1}: thumbnail upload failed non-fatally. ${error.message}`, 'warn');
          jobStore.updateClip(jobId, clip.id, { thumbnailStatus: 'failed' });
        }
      }

      jobStore.updateClip(jobId, clip.id, { status: 'done' });
      jobStore.log(jobId, `Clip ${index + 1}: complete.`);
    }

    jobStore.updateJob(jobId, { status: JOB_STATUS.DONE });
    jobStore.log(jobId, 'Pipeline complete.');
  } catch (error) {
    jobStore.updateJob(jobId, { status: JOB_STATUS.ERROR, error: error.message });
    jobStore.log(jobId, error.stack || error.message, 'error');
  } finally {
    await fs.rm(tempDir, { recursive: true, force: true });
    jobStore.log(jobId, 'Temporary files cleaned up.');
  }
}

async function exists(filePath) {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}
